In [4]:
import numpy as np

In [1]:
def gaussian_elimination(A, b):
    n = len(b)
    # Forward elimination
    for i in range(n):
    # Pivoting
        max_row = max(range(i, n), key=lambda x: abs(A[x][i]))
        A[i], A[max_row] = A[max_row], A[i]
        b[i], b[max_row] = b[max_row], b[i]
        # Make the rows below this one 0 in current column
        for j in range(i + 1, n):
            ratio = A[j][i] / A[i][i]
            A[j] = [A[j][k] - ratio * A[i][k] for k in range(n)]
            b[j] -= ratio * b[i]
            # Backward substitution
        x = [0] * n
    for i in range(n - 1, -1, -1):
        x[i] = (b[i] - sum(A[i][j] * x[j] for j in range(i + 1, n))) / A[i][i]
    return x



In [2]:
# Example Usage
A = [[2, 3, -1], [4, -2, 2], [-2, 1, 2]]
b = [5, 6, -1]
solution = gaussian_elimination(A, b)
print(f"Solution: {solution}")

Solution: [1.5833333333333333, 0.8333333333333333, 0.6666666666666666]


In [5]:
ans = np.linalg.solve(A,b)


In [6]:
print (ans)

[1.58333333 0.83333333 0.66666667]


In [14]:
import numpy as np

def lu_decomposition(A):
    n = len(A)
    L = np.eye(n)
    U = np.array(A, dtype=float)

    for i in range(n):
        if U[i, i] == 0:
            raise ValueError("Zero pivot encountered. LU decomposition cannot proceed.")

        for j in range(i + 1, n):
            factor = U[j, i] / U[i, i]
            L[j, i] = factor

            for k in range(i, n):
                U[j, k] -= factor * U[i, k]

    return L, U

In [15]:
# Example usage
A = np.array([[2, 3, 1],
[4, 7, -1],
[-2, 1, 2]])
L, U = lu_decomposition(A)
print("Matrix A:\n", A)
print("Lower Triangular Matrix L:\n", L)
print("Upper Triangular Matrix U:\n", U)

Matrix A:
 [[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
Lower Triangular Matrix L:
 [[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
Upper Triangular Matrix U:
 [[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]


In [11]:
from scipy.linalg import lu
P , L , U = lu(A)


In [16]:
print(A)
print(L)
print(U)

[[ 2  3  1]
 [ 4  7 -1]
 [-2  1  2]]
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
[[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]
